config/routes.rb
Rails.application.routes.draw do
  resources :storage_spaces, only: [ :index, :show, :new, :create ] do
    resources :bookings
  end
  # GET /storage_spaces          => :index
  # GET /storage_spaces/new      => :new
  # POST /storage_spaces         => :created
  # GET /storage_spaces/:id      => :show
  # GET /storage_spaces/:id/edit => :edit
  # PATCH /storage_spaces/:id    => :update
  # DELETE /storage_spaces/:id.  => :destroy

  devise_for :users
  root to: 'pages#home'

  get '/dashboard', to: 'pages#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Attachinary::Engine => "/attachinary"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :storage_space
  # after_validation :set_price, if: (:space_required_changed? || :start_date_changed? || :end_date_changed?)

  private

  # def set_price
  #   self.price = space_required * (end_date - start_date).to_i
  # end
end

app/models/storage_space.rb
class StorageSpace < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings
  geocoded_by :location
  after_validation :geocode, if: :location_changed?
  validates :space, presence: true
  validates :photo, presence: true
  has_attachment :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :bookings
  has_many :storage_spaces
  has_attachment :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action do
    @storage_space = StorageSpace.find(params[:storage_space_id])
  end

  def index
    @bookings = Booking.all
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.storage_space = @storage_space
    if @booking.save
      redirect_to dashboard_path
    end
  end

  def new
    @booking = Booking.new
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  private

  def booking_params
    params.require(:booking).permit(:space_required, :start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @three_spaces = StorageSpace.all.sample(3)
  end

  def dashboard
    @user = current_user
  end
end

app/controllers/storage_space_controller.rb
class StorageSpaceController < ApplicationController
  def index
    @storage_space = StorageSpace.near(params[:location], 50).where('space >= ?', params[:size] || 0)
  end

  # .near(params[:location], 50)

  def create
    @storage_space = StorageSpace.new(storage_space_params)
    @storage_space.save
  end

  def update
    @storage_space = StorageSpace.find(params[:id])
    @storage_space.update(storage_space_params)
    redirect_to storage_space_path(@storage_space)
  end

  private

  def storage_space_params
    params.require(:storage_space).permit(:username)
  end
end

app/controllers/storage_spaces_controller.rb
class StorageSpacesController < ApplicationController
  before_action :set_storage_space, only: [ :show, :update ]

  def index
    @storage_space = StorageSpace.near(params[:location], 50).where('space >= ?', (params[:size].blank? ? 0 : params[:size]))
  end

# @flats = Flat.where.not(latitude: nil, longitude: nil)

#     @hash = Gmaps4rails.build_markers(@flats) do |flat, marker|
#       marker.lat flat.latitude
#       marker.lng flat.longitude
#       # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
#     end
  # .near(params[:location], 50) STILL NEEDS LOGIC IN CASE FIELD LEFT BLANK

  def create
    @storage_space = StorageSpace.new(storage_space_params)
    @storage_space.user = current_user
    if @storage_space.save
      redirect_to storage_space_path(@storage_space)
    else
      render :new
    end
  end

  def new
    @storage_space = StorageSpace.new
  end

  def update

    @storage_space.update(storage_space_params)
    redirect_to storage_space_path(@storage_space)
  end

  # GET /storage_spaces/:id
  def show
      @hash = Gmaps4rails.build_markers(@storage_space) do |storage_space, marker|
      marker.lat storage_space.latitude
      marker.lng storage_space.longitude
    end
  end

  private

  def storage_space_params
    params.require(:storage_space).permit(:location, :space, :photo)
  end

  def set_storage_space
    @storage_space = StorageSpace.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:user).permit(:username, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/storage_space_helper.rb
module StorageSpaceHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/new.html.erb
<h1>Create a new booking, store your shit.</h1>

<%= simple_form_for [@storage_space, @booking] do |f| %>
  <%= f.input :space_required, label: "How much space will you need?" %>
<!--   <p> this is where you would specify how long you want to store it</p>-->
  <%= f.input :start_date, label: "From which date?" %>
  <%= f.input :end_date, label: "Until which date?" %>

  <%= f.submit "submit", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Storage4S</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>Welcome back, <%= @user.username %></center></h1>
  <h2> Your storage space bookings: </h2>

  <div class="row">

    <% @user.bookings.each do |b| %>

    <div class="col-xs-12 col-sm-4">
    <div class="card">
    <h4><%= b.storage_space.location %></h4>
      <p>Space requested: <b><%= b.space_required %></b>  meters squared.</p>
      <p>From <%= b.start_date? ? b.start_date : "unspecified" %> until <%=  b.end_date? ? b.end_date : "unspecified" %></p>
      <p>Price: £<%= (b.space_required * (b.end_date - b.start_date).to_i)*20 %></p>
    </div>
    </div>
    <% end %>

  </div>

  <div class="row" style="margin-top: 30px;">
  <h2> Your spaces: </h2>

    <% @user.storage_spaces.each do |s| %>

    <div class="col-xs-12 col-sm-4">
    <div class="card">
    <h4><%= s.location %></h4>
      <p><b><%= s.space %></b> meters squared available.</p>
      <p><b><%= s.bookings.size %> </b> bookings have been made for this space.</p>
    </div>
    </div>
    <% end %>

  </div>

</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,310,68,0.3) 0%, rgba(0,40,51,0.5) 50%), url(<%= image_path 'storage.jpg' %>);">
  <div class="banner-content">
    <h1>Store your stuff</h1>
    <p>Store your stuff or turn apartment space into income</p>
    <%= form_tag storage_spaces_path, method: :get, class: 'form-inline' do %>
      <div class="input-group">
        <input type="text" name="location" placeholder="London" class="form-control"style="width: 100px; margin-right: 5px">
        <input type="text" name="size" placeholder="20" class="form-control" style="width: 100px">
        <div class="input-group-addon">sq. meters</div>
      </div>
      <button class="btn btn-primary">Find storage space</button>
    <% end %>
  </div>
</div>

<div class="container" style="margin-top: 100px; margin-bottom: 100px;">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="card">
        <%= @three_spaces.first.location %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card">
        <%= @three_spaces[1].location %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card">
        <%= @three_spaces.last.location %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- <div class="navbar-wagon">
  <%# link_to root_path, class: "navbar-wagon-brand" do %>
    <%# image_tag "airbnb_logo.png" %>
  <%# end %>


  <div class="navbar-wagon-right hidden-xs hidden-sm">

    # <%# link_to t(".top_call_to_action", default: "facebook"), "#", class: "btn-primary" %>
  </div> -->

<div id="footer" style="padding: 10px">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline" style="padding:10px;">
          <li><a href=""><i class="fa fa-youtube"></i></a></li>
          <li><a href=""><i class="fa fa-instagram"></i></a></li>
          <li><a href=""><i class="fa fa-facebook"></i></a></li>
          <li><a href=""><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-8 text-right" style="padding: 10px;">
        <p>storage 4 shit</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "airbnb_logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>



      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-user"></i> <span>Profile</span>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <span>Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i> <span>Log out</span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to "Login", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to "Become a Host", new_storage_space_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-sm hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/storage_space/index.html.erb
<h1><%=@storage_space.size %> locations match your criteria:</h1>

<div class="container">
  <div class="row">
    <% @storage_space.each do |s| %>
       <div class="card col-xs-12 col-sm-4">
          <p style="color: black">There's <%= s.space %> square meters of space at <%= s.location %></p>
       </div>
      <% end %>
  </div>
</div>

app/views/storage_spaces/index.html.erb
<div class="results">
<h1><center><%=@storage_space.size %> locations match your criteria:</center></h1>
</div>

<div class="container">
  <div class="row">
    <% @storage_space.each do |s| %>
       <%= link_to(storage_space_path(s.id), class: "col-xs-12 col-sm-4") do %>
       <div class="card">
          <h4 style="color: black"><%= s.space %> Square Meters </h4>
          <h4> <%= s.location %></h4>
       </div>
       <% end %>
      <% end %>
  </div>
</div>

app/views/storage_spaces/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3" id="create_storage">
      <%= simple_form_for [@storage_space] do |f| %>
      <%= f.input :location %>
      <%= f.input :space %>
      <%= f.input :photo, as: :attachinary %>
      <%= f.submit "submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/storage_spaces/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,231,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path @storage_space.photo.path, height: 300, width: 400, crop: :fill %>');">

  <div class="banner-content">
  <h1><strong><%= @storage_space.user.username %></strong></h1>
  <h3><%= @storage_space.location %></h3>

  <%= button_to "Book", new_storage_space_booking_path(@storage_space.id), method: 'get' %>
  </div>

</div>

  <div id="map" style="width: 100%; height: 200px;"></div>


<% content_for(:after_js) do %>
  <script type="text/javascript">
          $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
  });
    </script>
<% end %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.submit %>
  <%= f.input :photo, as: :attachinary %>
<% end %>

app/views/users/index.html.erb
<h2>Welcome back, <%= @user.name %> </h2>

<% if @product.photo? %>
  <%= cl_image_tag @product.photo.path, width: 200, height: 300, crop: :fill %>
<% end %>